### ISSUE TITLE
项目缺失了教程中的文件"creat_sql.txt"

### ISSUE THREAD

**Issue by qriosa** [myhhub/zero_knowledge_graph#1]
从您的教程网站（https://www.ljjyy.com/archives/2019/10/100591.html#1-Mysql%E5%BB%BA%E5%BA%93）转过来下载的项目文件里面缺少了您教程描述的文件。请问能提供一下文件吗？以便知道您数据库的结构。

**Comment by qriosa** [comment]
并且 GitHub的源码中提供的KBQA也缺失了些文件。没有找到“data/actorName.txt”

**Comment by myhhub** [comment]
https://github.com/myhhub/zero_knowledge_graph/blob/master/KBQA/patternREfO/data/actorName.txt

**Comment by myhhub** [comment]
> 并且 GitHub的源码中提供的KBQA也缺失了些文件。没有找到“data/actorName.txt”

https://github.com/myhhub/zero_knowledge_graph/blob/master/KBQA/patternREfO/data/actorName.txt

**Comment by myhhub** [comment]
> 从您的教程网站（[https://www.ljjyy.com/archives/2019/10/100591.html#1-Mysql%E5%BB%BA%E5%BA%93）转过来下载的项目文件里面确实了，您教程描述的文件。请问能提供一下文件吗？以便知道您数据库的结构。](https://www.ljjyy.com/archives/2019/10/100591.html#1-Mysql%E5%BB%BA%E5%BA%93%EF%BC%89%E8%BD%AC%E8%BF%87%E6%9D%A5%E4%B8%8B%E8%BD%BD%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%96%87%E4%BB%B6%E9%87%8C%E9%9D%A2%E7%A1%AE%E5%AE%9E%E4%BA%86%EF%BC%8C%E6%82%A8%E6%95%99%E7%A8%8B%E6%8F%8F%E8%BF%B0%E7%9A%84%E6%96%87%E4%BB%B6%E3%80%82%E8%AF%B7%E9%97%AE%E8%83%BD%E6%8F%90%E4%BE%9B%E4%B8%80%E4%B8%8B%E6%96%87%E4%BB%B6%E5%90%97%EF%BC%9F%E4%BB%A5%E4%BE%BF%E7%9F%A5%E9%81%93%E6%82%A8%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E7%BB%93%E6%9E%84%E3%80%82)

https://github.com/myhhub/zero_knowledge_graph/blob/master/ie/craw/craw_without_spider/mysql/creat_sql.txt

**Comment by qriosa** [comment]
> > 并且 GitHub的源码中提供的KBQA也缺失了些文件。没有找到“data/actorName.txt”
> 
> https://github.com/myhhub/zero_knowledge_graph/blob/master/KBQA/patternREfO/data/actorName.txt

好的，谢谢您提供的资源。
